# Generated by Django 6.0.2 on 2026-05-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Area',
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=25)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.area')),
            ],
        ),
    ]
