# Generated by Django 6.0.2 on 2026-05-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='Area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='units',
            name='Unit',
            field=models.CharField(max_length=50),
        ),
    ]
