# Generated by Django 6.0.2 on 2026-05-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_remove_teacher_area_area_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Area',
        ),
    ]
