# Generated by Django 6.0.2 on 2026-05-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_remove_subject_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Areas',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
