# Generated by Django 6.0.2 on 2026-05-08 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_rename_area_areas_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.areas')),
            ],
        ),
    ]
