# Generated by Django 6.0.2 on 2026-05-08 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0005_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(max_length=30)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.areas')),
            ],
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
