# Generated by Django 6.0.2 on 2026-05-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0006_courses_units_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Course',
            field=models.ManyToManyField(to='MyApp1.courses'),
        ),
    ]
