# Generated by Django 6.0.2 on 2026-05-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0007_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Area',
            field=models.ManyToManyField(to='MyApp1.areas'),
        ),
    ]
