# Generated by Django 6.0.2 on 2026-05-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0009_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course',
            field=models.CharField(max_length=100),
        ),
    ]
