# Generated by Django 6.0.2 on 2026-05-15 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0010_alter_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='Course',
            field=models.ForeignKey(default='everything', on_delete=django.db.models.deletion.CASCADE, to='MyApp1.courses'),
        ),
    ]
