# Generated by Django 6.0.2 on 2026-05-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0011_units_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='Area',
        ),
        migrations.AlterField(
            model_name='units',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.courses'),
        ),
    ]
