# Generated by Django 6.0.2 on 2026-05-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0012_remove_units_area_alter_units_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='Course',
        ),
    ]
